/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.beorn.onlinepayment.model.impl;

import com.beorn.onlinepayment.model.PaymentPlugin;
import com.beorn.onlinepayment.model.PaymentPluginModel;
import com.beorn.onlinepayment.model.PaymentPluginSoap;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.language.LanguageUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * The base model implementation for the PaymentPlugin service. Represents a row in the &quot;Payment_PaymentPlugin&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.beorn.onlinepayment.model.PaymentPluginModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PaymentPluginImpl}.
 * </p>
 *
 * @author Sebastien Meunier
 * @see PaymentPluginImpl
 * @see com.beorn.onlinepayment.model.PaymentPlugin
 * @see com.beorn.onlinepayment.model.PaymentPluginModel
 * @generated
 */
@JSON(strict = true)
public class PaymentPluginModelImpl extends BaseModelImpl<PaymentPlugin>
	implements PaymentPluginModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a payment plugin model instance should use the {@link com.beorn.onlinepayment.model.PaymentPlugin} interface instead.
	 */
	public static final String TABLE_NAME = "Payment_PaymentPlugin";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "paymentPluginId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "applicationId", Types.VARCHAR },
			{ "name", Types.VARCHAR },
			{ "pluginConfigParameters", Types.CLOB },
			{ "sellerConfigParameters", Types.CLOB },
			{ "pluginConfig", Types.CLOB },
			{ "configured", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table Payment_PaymentPlugin (uuid_ VARCHAR(75) null,companyId LONG,groupId LONG,userId LONG,paymentPluginId LONG not null primary key,createDate DATE null,modifiedDate DATE null,applicationId VARCHAR(255) null,name STRING null,pluginConfigParameters TEXT null,sellerConfigParameters TEXT null,pluginConfig TEXT null,configured BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table Payment_PaymentPlugin";
	public static final String ORDER_BY_JPQL = " ORDER BY paymentPlugin.modifiedDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY Payment_PaymentPlugin.modifiedDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.beorn.onlinepayment.model.PaymentPlugin"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.beorn.onlinepayment.model.PaymentPlugin"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.beorn.onlinepayment.model.PaymentPlugin"),
			true);
	public static long APPLICATIONID_COLUMN_BITMASK = 1L;
	public static long COMPANYID_COLUMN_BITMASK = 2L;
	public static long GROUPID_COLUMN_BITMASK = 4L;
	public static long UUID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static PaymentPlugin toModel(PaymentPluginSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		PaymentPlugin model = new PaymentPluginImpl();

		model.setUuid(soapModel.getUuid());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setPaymentPluginId(soapModel.getPaymentPluginId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setApplicationId(soapModel.getApplicationId());
		model.setName(soapModel.getName());
		model.setPluginConfigParameters(soapModel.getPluginConfigParameters());
		model.setSellerConfigParameters(soapModel.getSellerConfigParameters());
		model.setPluginConfig(soapModel.getPluginConfig());
		model.setConfigured(soapModel.getConfigured());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<PaymentPlugin> toModels(PaymentPluginSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<PaymentPlugin> models = new ArrayList<PaymentPlugin>(soapModels.length);

		for (PaymentPluginSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final String MAPPING_TABLE_PAYMENT_PAYMENTPLUGIN_PAYMENTMETHOD_NAME =
		"Payment_PaymentPlugin_PaymentMethod";
	public static final Object[][] MAPPING_TABLE_PAYMENT_PAYMENTPLUGIN_PAYMENTMETHOD_COLUMNS =
		{
			{ "paymentPluginId", Types.BIGINT },
			{ "paymentMethodId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_PAYMENT_PAYMENTPLUGIN_PAYMENTMETHOD_SQL_CREATE =
		"create table Payment_PaymentPlugin_PaymentMethod (paymentPluginId LONG not null,paymentMethodId LONG not null,primary key (paymentPluginId, paymentMethodId))";
	public static final boolean FINDER_CACHE_ENABLED_PAYMENT_PAYMENTPLUGIN_PAYMENTMETHOD =
		GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.Payment_PaymentPlugin_PaymentMethod"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.beorn.onlinepayment.model.PaymentPlugin"));

	public PaymentPluginModelImpl() {
	}

	public long getPrimaryKey() {
		return _paymentPluginId;
	}

	public void setPrimaryKey(long primaryKey) {
		setPaymentPluginId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_paymentPluginId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return PaymentPlugin.class;
	}

	public String getModelClassName() {
		return PaymentPlugin.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("paymentPluginId", getPaymentPluginId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("applicationId", getApplicationId());
		attributes.put("name", getName());
		attributes.put("pluginConfigParameters", getPluginConfigParameters());
		attributes.put("sellerConfigParameters", getSellerConfigParameters());
		attributes.put("pluginConfig", getPluginConfig());
		attributes.put("configured", getConfigured());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long paymentPluginId = (Long)attributes.get("paymentPluginId");

		if (paymentPluginId != null) {
			setPaymentPluginId(paymentPluginId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String applicationId = (String)attributes.get("applicationId");

		if (applicationId != null) {
			setApplicationId(applicationId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String pluginConfigParameters = (String)attributes.get(
				"pluginConfigParameters");

		if (pluginConfigParameters != null) {
			setPluginConfigParameters(pluginConfigParameters);
		}

		String sellerConfigParameters = (String)attributes.get(
				"sellerConfigParameters");

		if (sellerConfigParameters != null) {
			setSellerConfigParameters(sellerConfigParameters);
		}

		String pluginConfig = (String)attributes.get("pluginConfig");

		if (pluginConfig != null) {
			setPluginConfig(pluginConfig);
		}

		Boolean configured = (Boolean)attributes.get("configured");

		if (configured != null) {
			setConfigured(configured);
		}
	}

	@JSON
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	public long getPaymentPluginId() {
		return _paymentPluginId;
	}

	public void setPaymentPluginId(long paymentPluginId) {
		_paymentPluginId = paymentPluginId;
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_columnBitmask = -1L;

		_modifiedDate = modifiedDate;
	}

	@JSON
	public String getApplicationId() {
		if (_applicationId == null) {
			return StringPool.BLANK;
		}
		else {
			return _applicationId;
		}
	}

	public void setApplicationId(String applicationId) {
		_columnBitmask |= APPLICATIONID_COLUMN_BITMASK;

		if (_originalApplicationId == null) {
			_originalApplicationId = _applicationId;
		}

		_applicationId = applicationId;
	}

	public String getOriginalApplicationId() {
		return GetterUtil.getString(_originalApplicationId);
	}

	@JSON
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public String getName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId);
	}

	public String getName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId, useDefault);
	}

	public String getName(String languageId) {
		return LocalizationUtil.getLocalization(getName(), languageId);
	}

	public String getName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getName(), languageId,
			useDefault);
	}

	public String getNameCurrentLanguageId() {
		return _nameCurrentLanguageId;
	}

	@JSON
	public String getNameCurrentValue() {
		Locale locale = getLocale(_nameCurrentLanguageId);

		return getName(locale);
	}

	public Map<Locale, String> getNameMap() {
		return LocalizationUtil.getLocalizationMap(getName());
	}

	public void setName(String name) {
		_name = name;
	}

	public void setName(String name, Locale locale) {
		setName(name, locale, LocaleUtil.getDefault());
	}

	public void setName(String name, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(name)) {
			setName(LocalizationUtil.updateLocalization(getName(), "Name",
					name, languageId, defaultLanguageId));
		}
		else {
			setName(LocalizationUtil.removeLocalization(getName(), "Name",
					languageId));
		}
	}

	public void setNameCurrentLanguageId(String languageId) {
		_nameCurrentLanguageId = languageId;
	}

	public void setNameMap(Map<Locale, String> nameMap) {
		setNameMap(nameMap, LocaleUtil.getDefault());
	}

	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale) {
		if (nameMap == null) {
			return;
		}

		Locale[] locales = LanguageUtil.getAvailableLocales();

		for (Locale locale : locales) {
			String name = nameMap.get(locale);

			setName(name, locale, defaultLocale);
		}
	}

	@JSON
	public String getPluginConfigParameters() {
		if (_pluginConfigParameters == null) {
			return StringPool.BLANK;
		}
		else {
			return _pluginConfigParameters;
		}
	}

	public void setPluginConfigParameters(String pluginConfigParameters) {
		_pluginConfigParameters = pluginConfigParameters;
	}

	@JSON
	public String getSellerConfigParameters() {
		if (_sellerConfigParameters == null) {
			return StringPool.BLANK;
		}
		else {
			return _sellerConfigParameters;
		}
	}

	public void setSellerConfigParameters(String sellerConfigParameters) {
		_sellerConfigParameters = sellerConfigParameters;
	}

	@JSON
	public String getPluginConfig() {
		if (_pluginConfig == null) {
			return StringPool.BLANK;
		}
		else {
			return _pluginConfig;
		}
	}

	public void setPluginConfig(String pluginConfig) {
		_pluginConfig = pluginConfig;
	}

	@JSON
	public boolean getConfigured() {
		return _configured;
	}

	public boolean isConfigured() {
		return _configured;
	}

	public void setConfigured(boolean configured) {
		_configured = configured;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			PaymentPlugin.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {
		setName(getName(defaultImportLocale), defaultImportLocale,
			defaultImportLocale);
	}

	@Override
	public PaymentPlugin toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (PaymentPlugin)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		PaymentPluginImpl paymentPluginImpl = new PaymentPluginImpl();

		paymentPluginImpl.setUuid(getUuid());
		paymentPluginImpl.setCompanyId(getCompanyId());
		paymentPluginImpl.setGroupId(getGroupId());
		paymentPluginImpl.setUserId(getUserId());
		paymentPluginImpl.setPaymentPluginId(getPaymentPluginId());
		paymentPluginImpl.setCreateDate(getCreateDate());
		paymentPluginImpl.setModifiedDate(getModifiedDate());
		paymentPluginImpl.setApplicationId(getApplicationId());
		paymentPluginImpl.setName(getName());
		paymentPluginImpl.setPluginConfigParameters(getPluginConfigParameters());
		paymentPluginImpl.setSellerConfigParameters(getSellerConfigParameters());
		paymentPluginImpl.setPluginConfig(getPluginConfig());
		paymentPluginImpl.setConfigured(getConfigured());

		paymentPluginImpl.resetOriginalValues();

		return paymentPluginImpl;
	}

	public int compareTo(PaymentPlugin paymentPlugin) {
		int value = 0;

		value = DateUtil.compareTo(getModifiedDate(),
				paymentPlugin.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		PaymentPlugin paymentPlugin = null;

		try {
			paymentPlugin = (PaymentPlugin)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = paymentPlugin.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		PaymentPluginModelImpl paymentPluginModelImpl = this;

		paymentPluginModelImpl._originalUuid = paymentPluginModelImpl._uuid;

		paymentPluginModelImpl._originalCompanyId = paymentPluginModelImpl._companyId;

		paymentPluginModelImpl._setOriginalCompanyId = false;

		paymentPluginModelImpl._originalGroupId = paymentPluginModelImpl._groupId;

		paymentPluginModelImpl._setOriginalGroupId = false;

		paymentPluginModelImpl._originalApplicationId = paymentPluginModelImpl._applicationId;

		paymentPluginModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PaymentPlugin> toCacheModel() {
		PaymentPluginCacheModel paymentPluginCacheModel = new PaymentPluginCacheModel();

		paymentPluginCacheModel.uuid = getUuid();

		String uuid = paymentPluginCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			paymentPluginCacheModel.uuid = null;
		}

		paymentPluginCacheModel.companyId = getCompanyId();

		paymentPluginCacheModel.groupId = getGroupId();

		paymentPluginCacheModel.userId = getUserId();

		paymentPluginCacheModel.paymentPluginId = getPaymentPluginId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			paymentPluginCacheModel.createDate = createDate.getTime();
		}
		else {
			paymentPluginCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			paymentPluginCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			paymentPluginCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		paymentPluginCacheModel.applicationId = getApplicationId();

		String applicationId = paymentPluginCacheModel.applicationId;

		if ((applicationId != null) && (applicationId.length() == 0)) {
			paymentPluginCacheModel.applicationId = null;
		}

		paymentPluginCacheModel.name = getName();

		String name = paymentPluginCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			paymentPluginCacheModel.name = null;
		}

		paymentPluginCacheModel.pluginConfigParameters = getPluginConfigParameters();

		String pluginConfigParameters = paymentPluginCacheModel.pluginConfigParameters;

		if ((pluginConfigParameters != null) &&
				(pluginConfigParameters.length() == 0)) {
			paymentPluginCacheModel.pluginConfigParameters = null;
		}

		paymentPluginCacheModel.sellerConfigParameters = getSellerConfigParameters();

		String sellerConfigParameters = paymentPluginCacheModel.sellerConfigParameters;

		if ((sellerConfigParameters != null) &&
				(sellerConfigParameters.length() == 0)) {
			paymentPluginCacheModel.sellerConfigParameters = null;
		}

		paymentPluginCacheModel.pluginConfig = getPluginConfig();

		String pluginConfig = paymentPluginCacheModel.pluginConfig;

		if ((pluginConfig != null) && (pluginConfig.length() == 0)) {
			paymentPluginCacheModel.pluginConfig = null;
		}

		paymentPluginCacheModel.configured = getConfigured();

		return paymentPluginCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", paymentPluginId=");
		sb.append(getPaymentPluginId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", applicationId=");
		sb.append(getApplicationId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", pluginConfigParameters=");
		sb.append(getPluginConfigParameters());
		sb.append(", sellerConfigParameters=");
		sb.append(getSellerConfigParameters());
		sb.append(", pluginConfig=");
		sb.append(getPluginConfig());
		sb.append(", configured=");
		sb.append(getConfigured());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("com.beorn.onlinepayment.model.PaymentPlugin");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>paymentPluginId</column-name><column-value><![CDATA[");
		sb.append(getPaymentPluginId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>applicationId</column-name><column-value><![CDATA[");
		sb.append(getApplicationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pluginConfigParameters</column-name><column-value><![CDATA[");
		sb.append(getPluginConfigParameters());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sellerConfigParameters</column-name><column-value><![CDATA[");
		sb.append(getSellerConfigParameters());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pluginConfig</column-name><column-value><![CDATA[");
		sb.append(getPluginConfig());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>configured</column-name><column-value><![CDATA[");
		sb.append(getConfigured());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PaymentPlugin.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			PaymentPlugin.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private String _userUuid;
	private long _paymentPluginId;
	private Date _createDate;
	private Date _modifiedDate;
	private String _applicationId;
	private String _originalApplicationId;
	private String _name;
	private String _nameCurrentLanguageId;
	private String _pluginConfigParameters;
	private String _sellerConfigParameters;
	private String _pluginConfig;
	private boolean _configured;
	private long _columnBitmask;
	private PaymentPlugin _escapedModelProxy;
}