/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.beorn.onlinepayment.model.impl;

import com.beorn.onlinepayment.model.TransactionParameter;
import com.beorn.onlinepayment.model.TransactionParameterModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the TransactionParameter service. Represents a row in the &quot;Payment_TransactionParameter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.beorn.onlinepayment.model.TransactionParameterModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TransactionParameterImpl}.
 * </p>
 *
 * @author Sebastien Meunier
 * @see TransactionParameterImpl
 * @see com.beorn.onlinepayment.model.TransactionParameter
 * @see com.beorn.onlinepayment.model.TransactionParameterModel
 * @generated
 */
public class TransactionParameterModelImpl extends BaseModelImpl<TransactionParameter>
	implements TransactionParameterModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a transaction parameter model instance should use the {@link com.beorn.onlinepayment.model.TransactionParameter} interface instead.
	 */
	public static final String TABLE_NAME = "Payment_TransactionParameter";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "transactionParameterId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "transactionId", Types.BIGINT },
			{ "key_", Types.VARCHAR },
			{ "value", Types.CLOB }
		};
	public static final String TABLE_SQL_CREATE = "create table Payment_TransactionParameter (uuid_ VARCHAR(75) null,companyId LONG,groupId LONG,userId LONG,transactionParameterId LONG not null primary key,createDate DATE null,modifiedDate DATE null,transactionId LONG,key_ VARCHAR(255) null,value TEXT null)";
	public static final String TABLE_SQL_DROP = "drop table Payment_TransactionParameter";
	public static final String ORDER_BY_JPQL = " ORDER BY transactionParameter.modifiedDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY Payment_TransactionParameter.modifiedDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.beorn.onlinepayment.model.TransactionParameter"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.beorn.onlinepayment.model.TransactionParameter"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.beorn.onlinepayment.model.TransactionParameter"),
			true);
	public static long GROUPID_COLUMN_BITMASK = 1L;
	public static long KEY_COLUMN_BITMASK = 2L;
	public static long TRANSACTIONID_COLUMN_BITMASK = 4L;
	public static long UUID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.beorn.onlinepayment.model.TransactionParameter"));

	public TransactionParameterModelImpl() {
	}

	public long getPrimaryKey() {
		return _transactionParameterId;
	}

	public void setPrimaryKey(long primaryKey) {
		setTransactionParameterId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_transactionParameterId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return TransactionParameter.class;
	}

	public String getModelClassName() {
		return TransactionParameter.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("transactionParameterId", getTransactionParameterId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("transactionId", getTransactionId());
		attributes.put("key", getKey());
		attributes.put("value", getValue());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long transactionParameterId = (Long)attributes.get(
				"transactionParameterId");

		if (transactionParameterId != null) {
			setTransactionParameterId(transactionParameterId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long transactionId = (Long)attributes.get("transactionId");

		if (transactionId != null) {
			setTransactionId(transactionId);
		}

		String key = (String)attributes.get("key");

		if (key != null) {
			setKey(key);
		}

		String value = (String)attributes.get("value");

		if (value != null) {
			setValue(value);
		}
	}

	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getTransactionParameterId() {
		return _transactionParameterId;
	}

	public void setTransactionParameterId(long transactionParameterId) {
		_transactionParameterId = transactionParameterId;
	}

	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_columnBitmask = -1L;

		_modifiedDate = modifiedDate;
	}

	public long getTransactionId() {
		return _transactionId;
	}

	public void setTransactionId(long transactionId) {
		_columnBitmask |= TRANSACTIONID_COLUMN_BITMASK;

		if (!_setOriginalTransactionId) {
			_setOriginalTransactionId = true;

			_originalTransactionId = _transactionId;
		}

		_transactionId = transactionId;
	}

	public long getOriginalTransactionId() {
		return _originalTransactionId;
	}

	public String getKey() {
		if (_key == null) {
			return StringPool.BLANK;
		}
		else {
			return _key;
		}
	}

	public void setKey(String key) {
		_columnBitmask |= KEY_COLUMN_BITMASK;

		if (_originalKey == null) {
			_originalKey = _key;
		}

		_key = key;
	}

	public String getOriginalKey() {
		return GetterUtil.getString(_originalKey);
	}

	public String getValue() {
		if (_value == null) {
			return StringPool.BLANK;
		}
		else {
			return _value;
		}
	}

	public void setValue(String value) {
		_value = value;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			TransactionParameter.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TransactionParameter toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (TransactionParameter)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		TransactionParameterImpl transactionParameterImpl = new TransactionParameterImpl();

		transactionParameterImpl.setUuid(getUuid());
		transactionParameterImpl.setCompanyId(getCompanyId());
		transactionParameterImpl.setGroupId(getGroupId());
		transactionParameterImpl.setUserId(getUserId());
		transactionParameterImpl.setTransactionParameterId(getTransactionParameterId());
		transactionParameterImpl.setCreateDate(getCreateDate());
		transactionParameterImpl.setModifiedDate(getModifiedDate());
		transactionParameterImpl.setTransactionId(getTransactionId());
		transactionParameterImpl.setKey(getKey());
		transactionParameterImpl.setValue(getValue());

		transactionParameterImpl.resetOriginalValues();

		return transactionParameterImpl;
	}

	public int compareTo(TransactionParameter transactionParameter) {
		int value = 0;

		value = DateUtil.compareTo(getModifiedDate(),
				transactionParameter.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		TransactionParameter transactionParameter = null;

		try {
			transactionParameter = (TransactionParameter)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = transactionParameter.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TransactionParameterModelImpl transactionParameterModelImpl = this;

		transactionParameterModelImpl._originalUuid = transactionParameterModelImpl._uuid;

		transactionParameterModelImpl._originalGroupId = transactionParameterModelImpl._groupId;

		transactionParameterModelImpl._setOriginalGroupId = false;

		transactionParameterModelImpl._originalTransactionId = transactionParameterModelImpl._transactionId;

		transactionParameterModelImpl._setOriginalTransactionId = false;

		transactionParameterModelImpl._originalKey = transactionParameterModelImpl._key;

		transactionParameterModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TransactionParameter> toCacheModel() {
		TransactionParameterCacheModel transactionParameterCacheModel = new TransactionParameterCacheModel();

		transactionParameterCacheModel.uuid = getUuid();

		String uuid = transactionParameterCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			transactionParameterCacheModel.uuid = null;
		}

		transactionParameterCacheModel.companyId = getCompanyId();

		transactionParameterCacheModel.groupId = getGroupId();

		transactionParameterCacheModel.userId = getUserId();

		transactionParameterCacheModel.transactionParameterId = getTransactionParameterId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			transactionParameterCacheModel.createDate = createDate.getTime();
		}
		else {
			transactionParameterCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			transactionParameterCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			transactionParameterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		transactionParameterCacheModel.transactionId = getTransactionId();

		transactionParameterCacheModel.key = getKey();

		String key = transactionParameterCacheModel.key;

		if ((key != null) && (key.length() == 0)) {
			transactionParameterCacheModel.key = null;
		}

		transactionParameterCacheModel.value = getValue();

		String value = transactionParameterCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			transactionParameterCacheModel.value = null;
		}

		return transactionParameterCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", transactionParameterId=");
		sb.append(getTransactionParameterId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", transactionId=");
		sb.append(getTransactionId());
		sb.append(", key=");
		sb.append(getKey());
		sb.append(", value=");
		sb.append(getValue());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.beorn.onlinepayment.model.TransactionParameter");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>transactionParameterId</column-name><column-value><![CDATA[");
		sb.append(getTransactionParameterId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>transactionId</column-name><column-value><![CDATA[");
		sb.append(getTransactionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>key</column-name><column-value><![CDATA[");
		sb.append(getKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>value</column-name><column-value><![CDATA[");
		sb.append(getValue());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TransactionParameter.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			TransactionParameter.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _companyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private String _userUuid;
	private long _transactionParameterId;
	private Date _createDate;
	private Date _modifiedDate;
	private long _transactionId;
	private long _originalTransactionId;
	private boolean _setOriginalTransactionId;
	private String _key;
	private String _originalKey;
	private String _value;
	private long _columnBitmask;
	private TransactionParameter _escapedModelProxy;
}