/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.beorn.onlinepayment.model;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the PaymentMethod service. Represents a row in the &quot;Payment_PaymentMethod&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.beorn.onlinepayment.model.impl.PaymentMethodModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.beorn.onlinepayment.model.impl.PaymentMethodImpl}.
 * </p>
 *
 * @author Sebastien Meunier
 * @see PaymentMethod
 * @see com.beorn.onlinepayment.model.impl.PaymentMethodImpl
 * @see com.beorn.onlinepayment.model.impl.PaymentMethodModelImpl
 * @generated
 */
public interface PaymentMethodModel extends BaseModel<PaymentMethod> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a payment method model instance should use the {@link PaymentMethod} interface instead.
	 */

	/**
	 * Returns the primary key of this payment method.
	 *
	 * @return the primary key of this payment method
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this payment method.
	 *
	 * @param primaryKey the primary key of this payment method
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this payment method.
	 *
	 * @return the uuid of this payment method
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this payment method.
	 *
	 * @param uuid the uuid of this payment method
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the company ID of this payment method.
	 *
	 * @return the company ID of this payment method
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this payment method.
	 *
	 * @param companyId the company ID of this payment method
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this payment method.
	 *
	 * @return the group ID of this payment method
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this payment method.
	 *
	 * @param groupId the group ID of this payment method
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this payment method.
	 *
	 * @return the user ID of this payment method
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this payment method.
	 *
	 * @param userId the user ID of this payment method
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this payment method.
	 *
	 * @return the user uuid of this payment method
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this payment method.
	 *
	 * @param userUuid the user uuid of this payment method
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the payment method ID of this payment method.
	 *
	 * @return the payment method ID of this payment method
	 */
	public long getPaymentMethodId();

	/**
	 * Sets the payment method ID of this payment method.
	 *
	 * @param paymentMethodId the payment method ID of this payment method
	 */
	public void setPaymentMethodId(long paymentMethodId);

	/**
	 * Returns the create date of this payment method.
	 *
	 * @return the create date of this payment method
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this payment method.
	 *
	 * @param createDate the create date of this payment method
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this payment method.
	 *
	 * @return the modified date of this payment method
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this payment method.
	 *
	 * @param modifiedDate the modified date of this payment method
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the key of this payment method.
	 *
	 * @return the key of this payment method
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this payment method.
	 *
	 * @param key the key of this payment method
	 */
	public void setKey(String key);

	/**
	 * Returns the name of this payment method.
	 *
	 * @return the name of this payment method
	 */
	public String getName();

	/**
	 * Returns the localized name of this payment method in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized name of this payment method
	 */
	@AutoEscape
	public String getName(Locale locale);

	/**
	 * Returns the localized name of this payment method in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this payment method. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized name of this payment method in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized name of this payment method
	 */
	@AutoEscape
	public String getName(String languageId);

	/**
	 * Returns the localized name of this payment method in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this payment method
	 */
	@AutoEscape
	public String getName(String languageId, boolean useDefault);

	@AutoEscape
	public String getNameCurrentLanguageId();

	@AutoEscape
	public String getNameCurrentValue();

	/**
	 * Returns a map of the locales and localized names of this payment method.
	 *
	 * @return the locales and localized names of this payment method
	 */
	public Map<Locale, String> getNameMap();

	/**
	 * Sets the name of this payment method.
	 *
	 * @param name the name of this payment method
	 */
	public void setName(String name);

	/**
	 * Sets the localized name of this payment method in the language.
	 *
	 * @param name the localized name of this payment method
	 * @param locale the locale of the language
	 */
	public void setName(String name, Locale locale);

	/**
	 * Sets the localized name of this payment method in the language, and sets the default locale.
	 *
	 * @param name the localized name of this payment method
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setName(String name, Locale locale, Locale defaultLocale);

	public void setNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized names of this payment method from the map of locales and localized names.
	 *
	 * @param nameMap the locales and localized names of this payment method
	 */
	public void setNameMap(Map<Locale, String> nameMap);

	/**
	 * Sets the localized names of this payment method from the map of locales and localized names, and sets the default locale.
	 *
	 * @param nameMap the locales and localized names of this payment method
	 * @param defaultLocale the default locale
	 */
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	public Object clone();

	public int compareTo(PaymentMethod paymentMethod);

	public int hashCode();

	public CacheModel<PaymentMethod> toCacheModel();

	public PaymentMethod toEscapedModel();

	public String toString();

	public String toXmlString();
}