/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.beorn.onlinepayment.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Rule service. Represents a row in the &quot;Payment_Rule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.beorn.onlinepayment.model.impl.RuleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.beorn.onlinepayment.model.impl.RuleImpl}.
 * </p>
 *
 * @author Sebastien Meunier
 * @see Rule
 * @see com.beorn.onlinepayment.model.impl.RuleImpl
 * @see com.beorn.onlinepayment.model.impl.RuleModelImpl
 * @generated
 */
public interface RuleModel extends BaseModel<Rule> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rule model instance should use the {@link Rule} interface instead.
	 */

	/**
	 * Returns the primary key of this rule.
	 *
	 * @return the primary key of this rule
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rule.
	 *
	 * @param primaryKey the primary key of this rule
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this rule.
	 *
	 * @return the uuid of this rule
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this rule.
	 *
	 * @param uuid the uuid of this rule
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the company ID of this rule.
	 *
	 * @return the company ID of this rule
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this rule.
	 *
	 * @param companyId the company ID of this rule
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this rule.
	 *
	 * @return the group ID of this rule
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this rule.
	 *
	 * @param groupId the group ID of this rule
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this rule.
	 *
	 * @return the user ID of this rule
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this rule.
	 *
	 * @param userId the user ID of this rule
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this rule.
	 *
	 * @return the user uuid of this rule
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this rule.
	 *
	 * @param userUuid the user uuid of this rule
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the rule ID of this rule.
	 *
	 * @return the rule ID of this rule
	 */
	public long getRuleId();

	/**
	 * Sets the rule ID of this rule.
	 *
	 * @param ruleId the rule ID of this rule
	 */
	public void setRuleId(long ruleId);

	/**
	 * Returns the create date of this rule.
	 *
	 * @return the create date of this rule
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this rule.
	 *
	 * @param createDate the create date of this rule
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this rule.
	 *
	 * @return the modified date of this rule
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this rule.
	 *
	 * @param modifiedDate the modified date of this rule
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the payment plugin config ID of this rule.
	 *
	 * @return the payment plugin config ID of this rule
	 */
	public long getPaymentPluginConfigId();

	/**
	 * Sets the payment plugin config ID of this rule.
	 *
	 * @param paymentPluginConfigId the payment plugin config ID of this rule
	 */
	public void setPaymentPluginConfigId(long paymentPluginConfigId);

	/**
	 * Returns the content of this rule.
	 *
	 * @return the content of this rule
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this rule.
	 *
	 * @param content the content of this rule
	 */
	public void setContent(String content);

	/**
	 * Returns the priority of this rule.
	 *
	 * @return the priority of this rule
	 */
	public int getPriority();

	/**
	 * Sets the priority of this rule.
	 *
	 * @param priority the priority of this rule
	 */
	public void setPriority(int priority);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Rule rule);

	public int hashCode();

	public CacheModel<Rule> toCacheModel();

	public Rule toEscapedModel();

	public String toString();

	public String toXmlString();
}