/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.beorn.onlinepayment.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Seller service. Represents a row in the &quot;Payment_Seller&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.beorn.onlinepayment.model.impl.SellerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.beorn.onlinepayment.model.impl.SellerImpl}.
 * </p>
 *
 * @author Sebastien Meunier
 * @see Seller
 * @see com.beorn.onlinepayment.model.impl.SellerImpl
 * @see com.beorn.onlinepayment.model.impl.SellerModelImpl
 * @generated
 */
public interface SellerModel extends BaseModel<Seller> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a seller model instance should use the {@link Seller} interface instead.
	 */

	/**
	 * Returns the primary key of this seller.
	 *
	 * @return the primary key of this seller
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this seller.
	 *
	 * @param primaryKey the primary key of this seller
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this seller.
	 *
	 * @return the uuid of this seller
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this seller.
	 *
	 * @param uuid the uuid of this seller
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the company ID of this seller.
	 *
	 * @return the company ID of this seller
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this seller.
	 *
	 * @param companyId the company ID of this seller
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this seller.
	 *
	 * @return the group ID of this seller
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this seller.
	 *
	 * @param groupId the group ID of this seller
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this seller.
	 *
	 * @return the user ID of this seller
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this seller.
	 *
	 * @param userId the user ID of this seller
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this seller.
	 *
	 * @return the user uuid of this seller
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this seller.
	 *
	 * @param userUuid the user uuid of this seller
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the seller ID of this seller.
	 *
	 * @return the seller ID of this seller
	 */
	public long getSellerId();

	/**
	 * Sets the seller ID of this seller.
	 *
	 * @param sellerId the seller ID of this seller
	 */
	public void setSellerId(long sellerId);

	/**
	 * Returns the create date of this seller.
	 *
	 * @return the create date of this seller
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this seller.
	 *
	 * @param createDate the create date of this seller
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this seller.
	 *
	 * @return the modified date of this seller
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this seller.
	 *
	 * @param modifiedDate the modified date of this seller
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this seller.
	 *
	 * @return the name of this seller
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this seller.
	 *
	 * @param name the name of this seller
	 */
	public void setName(String name);

	/**
	 * Returns the active of this seller.
	 *
	 * @return the active of this seller
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this seller is active.
	 *
	 * @return <code>true</code> if this seller is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this seller is active.
	 *
	 * @param active the active of this seller
	 */
	public void setActive(boolean active);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Seller seller);

	public int hashCode();

	public CacheModel<Seller> toCacheModel();

	public Seller toEscapedModel();

	public String toString();

	public String toXmlString();
}