/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.beorn.onlinepayment.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Transaction service. Represents a row in the &quot;Payment_Transaction&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.beorn.onlinepayment.model.impl.TransactionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.beorn.onlinepayment.model.impl.TransactionImpl}.
 * </p>
 *
 * @author Sebastien Meunier
 * @see Transaction
 * @see com.beorn.onlinepayment.model.impl.TransactionImpl
 * @see com.beorn.onlinepayment.model.impl.TransactionModelImpl
 * @generated
 */
public interface TransactionModel extends BaseModel<Transaction> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a transaction model instance should use the {@link Transaction} interface instead.
	 */

	/**
	 * Returns the primary key of this transaction.
	 *
	 * @return the primary key of this transaction
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this transaction.
	 *
	 * @param primaryKey the primary key of this transaction
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this transaction.
	 *
	 * @return the uuid of this transaction
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this transaction.
	 *
	 * @param uuid the uuid of this transaction
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the company ID of this transaction.
	 *
	 * @return the company ID of this transaction
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this transaction.
	 *
	 * @param companyId the company ID of this transaction
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this transaction.
	 *
	 * @return the group ID of this transaction
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this transaction.
	 *
	 * @param groupId the group ID of this transaction
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this transaction.
	 *
	 * @return the user ID of this transaction
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this transaction.
	 *
	 * @param userId the user ID of this transaction
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this transaction.
	 *
	 * @return the user uuid of this transaction
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this transaction.
	 *
	 * @param userUuid the user uuid of this transaction
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the transaction ID of this transaction.
	 *
	 * @return the transaction ID of this transaction
	 */
	public long getTransactionId();

	/**
	 * Sets the transaction ID of this transaction.
	 *
	 * @param transactionId the transaction ID of this transaction
	 */
	public void setTransactionId(long transactionId);

	/**
	 * Returns the create date of this transaction.
	 *
	 * @return the create date of this transaction
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this transaction.
	 *
	 * @param createDate the create date of this transaction
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this transaction.
	 *
	 * @return the modified date of this transaction
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this transaction.
	 *
	 * @param modifiedDate the modified date of this transaction
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the application ID of this transaction.
	 *
	 * @return the application ID of this transaction
	 */
	@AutoEscape
	public String getApplicationId();

	/**
	 * Sets the application ID of this transaction.
	 *
	 * @param applicationId the application ID of this transaction
	 */
	public void setApplicationId(String applicationId);

	/**
	 * Returns the seller ID of this transaction.
	 *
	 * @return the seller ID of this transaction
	 */
	public long getSellerId();

	/**
	 * Sets the seller ID of this transaction.
	 *
	 * @param sellerId the seller ID of this transaction
	 */
	public void setSellerId(long sellerId);

	/**
	 * Returns the amount of this transaction.
	 *
	 * @return the amount of this transaction
	 */
	public double getAmount();

	/**
	 * Sets the amount of this transaction.
	 *
	 * @param amount the amount of this transaction
	 */
	public void setAmount(double amount);

	/**
	 * Returns the currency code of this transaction.
	 *
	 * @return the currency code of this transaction
	 */
	@AutoEscape
	public String getCurrencyCode();

	/**
	 * Sets the currency code of this transaction.
	 *
	 * @param currencyCode the currency code of this transaction
	 */
	public void setCurrencyCode(String currencyCode);

	/**
	 * Returns the status of this transaction.
	 *
	 * @return the status of this transaction
	 */
	public long getStatus();

	/**
	 * Sets the status of this transaction.
	 *
	 * @param status the status of this transaction
	 */
	public void setStatus(long status);

	/**
	 * Returns the payment application ID of this transaction.
	 *
	 * @return the payment application ID of this transaction
	 */
	@AutoEscape
	public String getPaymentApplicationId();

	/**
	 * Sets the payment application ID of this transaction.
	 *
	 * @param paymentApplicationId the payment application ID of this transaction
	 */
	public void setPaymentApplicationId(String paymentApplicationId);

	/**
	 * Returns the amount paid of this transaction.
	 *
	 * @return the amount paid of this transaction
	 */
	public double getAmountPaid();

	/**
	 * Sets the amount paid of this transaction.
	 *
	 * @param amountPaid the amount paid of this transaction
	 */
	public void setAmountPaid(double amountPaid);

	/**
	 * Returns the amount refunded of this transaction.
	 *
	 * @return the amount refunded of this transaction
	 */
	public double getAmountRefunded();

	/**
	 * Sets the amount refunded of this transaction.
	 *
	 * @param amountRefunded the amount refunded of this transaction
	 */
	public void setAmountRefunded(double amountRefunded);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Transaction transaction);

	public int hashCode();

	public CacheModel<Transaction> toCacheModel();

	public Transaction toEscapedModel();

	public String toString();

	public String toXmlString();
}