/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.beorn.onlinepayment.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TransactionParameter service. Represents a row in the &quot;Payment_TransactionParameter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.beorn.onlinepayment.model.impl.TransactionParameterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.beorn.onlinepayment.model.impl.TransactionParameterImpl}.
 * </p>
 *
 * @author Sebastien Meunier
 * @see TransactionParameter
 * @see com.beorn.onlinepayment.model.impl.TransactionParameterImpl
 * @see com.beorn.onlinepayment.model.impl.TransactionParameterModelImpl
 * @generated
 */
public interface TransactionParameterModel extends BaseModel<TransactionParameter> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a transaction parameter model instance should use the {@link TransactionParameter} interface instead.
	 */

	/**
	 * Returns the primary key of this transaction parameter.
	 *
	 * @return the primary key of this transaction parameter
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this transaction parameter.
	 *
	 * @param primaryKey the primary key of this transaction parameter
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this transaction parameter.
	 *
	 * @return the uuid of this transaction parameter
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this transaction parameter.
	 *
	 * @param uuid the uuid of this transaction parameter
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the company ID of this transaction parameter.
	 *
	 * @return the company ID of this transaction parameter
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this transaction parameter.
	 *
	 * @param companyId the company ID of this transaction parameter
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this transaction parameter.
	 *
	 * @return the group ID of this transaction parameter
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this transaction parameter.
	 *
	 * @param groupId the group ID of this transaction parameter
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this transaction parameter.
	 *
	 * @return the user ID of this transaction parameter
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this transaction parameter.
	 *
	 * @param userId the user ID of this transaction parameter
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this transaction parameter.
	 *
	 * @return the user uuid of this transaction parameter
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this transaction parameter.
	 *
	 * @param userUuid the user uuid of this transaction parameter
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the transaction parameter ID of this transaction parameter.
	 *
	 * @return the transaction parameter ID of this transaction parameter
	 */
	public long getTransactionParameterId();

	/**
	 * Sets the transaction parameter ID of this transaction parameter.
	 *
	 * @param transactionParameterId the transaction parameter ID of this transaction parameter
	 */
	public void setTransactionParameterId(long transactionParameterId);

	/**
	 * Returns the create date of this transaction parameter.
	 *
	 * @return the create date of this transaction parameter
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this transaction parameter.
	 *
	 * @param createDate the create date of this transaction parameter
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this transaction parameter.
	 *
	 * @return the modified date of this transaction parameter
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this transaction parameter.
	 *
	 * @param modifiedDate the modified date of this transaction parameter
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the transaction ID of this transaction parameter.
	 *
	 * @return the transaction ID of this transaction parameter
	 */
	public long getTransactionId();

	/**
	 * Sets the transaction ID of this transaction parameter.
	 *
	 * @param transactionId the transaction ID of this transaction parameter
	 */
	public void setTransactionId(long transactionId);

	/**
	 * Returns the key of this transaction parameter.
	 *
	 * @return the key of this transaction parameter
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this transaction parameter.
	 *
	 * @param key the key of this transaction parameter
	 */
	public void setKey(String key);

	/**
	 * Returns the value of this transaction parameter.
	 *
	 * @return the value of this transaction parameter
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this transaction parameter.
	 *
	 * @param value the value of this transaction parameter
	 */
	public void setValue(String value);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TransactionParameter transactionParameter);

	public int hashCode();

	public CacheModel<TransactionParameter> toCacheModel();

	public TransactionParameter toEscapedModel();

	public String toString();

	public String toXmlString();
}